[package]
name = "accelkeys"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "s" # 3 is fastest binary; use "s" for smallest
lto = true

[dependencies]
pathfinding = "^3"
