[package]
name = "accelhints"
version = "1.0.0"
edition = "2021"

[profile.release]
strip = true
opt-level = 3 # 3 is fastest binary; use "s" for smallest
lto = true

[dependencies]
pathfinding = "^3"
anyhow = "^1"
